services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: quotes_app
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - backend-db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quote-backend
    restart: always
    environment:
      DB_URI: mongodb://root:pass@mongodb:27017/quote_db?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - backend-db
      - frontend-backend
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: quote-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend-backend
networks:
  frontend-backend:
    driver: bridge
  backend-db:
    driver: bridge
volumes:
  db_data:
    driver: local
